spring:
    datasource:
      url: ${DB_URL}
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: ${DB_USER_NAME}
      password: ${DB_PASSWORD}

  # 태태 로컬 데이터베이스 설정
#    datasource:
#      url: jdbc:mysql://localhost:3306/bigbrother
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      username: root
#      password: 1234

    jpa:
      hibernate:
        ddl-auto: create-drop
      properties:
        hibernate:
          format_sql: true
          show_sql: true