server:
  port: 8080

spring:
  profiles:
    active: ${VARIABLE_NAME}
  main:
    debug: true

  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss
    serialization:
      write-dates-as-timestamps: false
    time-zone: Asia/Seoul

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GOOGLE_ACCOUNT}
    password: ${APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

      auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30분
  data:
    redis:
      port: 6379
      host: localhost

  servlet:
    multipart:
      enabled: true
      max-request-size: 300MB
      max-file-size: 300MB


jwt:
  secret: ${JWT_SECRET}

cloud:
  aws:
    s3:
      bucket: big-brother-storage
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false

ssh:
  remote-host: ${SSH_REMOTE_HOST}
  ssh-port: 22
  user-name: ${SSH_USER_NAME}
  private-key-path: ${SSH_PRIVATE_KEY_PATH}

