server:
  port: 8080

spring:
  main:
    debug: true

  datasource:
    url: ${DB_URL}
    username: ${DB_NAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 로컬디비 - 태태
  #datasource:
   # url: jdbc:mysql://localhost:3306/bigbrother?serverTimezone=UTC
   # driver-class-name: com.mysql.cj.jdbc.Driver
   # username: root
   # password: 1234

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
        show_sql: true

jwt:
  secret: ${JWT_SECRET}

